apiVersion: component.kubesphere.io/v1alpha1
kind: Component
metadata:
  name: secrets
spec:
  enabled: true
  selector:
    matchLabels:
      component.kubesphere.io/name: secrets
      component.kubesphere.io/version: v0.1.0
  componentKinds:
    - group: component.kubesphere.io
      kind: APIService

---
apiVersion: component.kubesphere.io/v1alpha1
kind: APIService
metadata:
  name: secrets
  labels:
    component.kubesphere.io/name: secrets
    component.kubesphere.io/version: v0.1.0
spec:
  group: resources.demo.io
  version: v1alpha1
  insecureSkipTLSVerify: false
  nonResourceURLs:
    - /demo.io/metrics
  endpoint: http://localhost:1090
status:
  enabled: true
