apiVersion: v1
kind: Service
metadata:
  name: apiserver
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "secrets.selectorLabels" . | nindent 4 }}
