# permissions for end users to edit secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-editor-role
rules:
- apiGroups:
  - resources.kubesphere.io
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.kubesphere.io
  resources:
  - secrets/status
  verbs:
  - get
